### ISSUE TITLE
Can I use a <figure> element?

### ISSUE THREAD

**Issue by Swissendo** [miromannino/Justified-Gallery#100]
My current markup uses the ```<figure>``` tag instead of an ```<div>``` to wrap the images in, as this seems the more common and "correct" way to do this. Sadly, the plugin doesn't seem to work with this markup and doesn't add the class *jg-entry* to the tag. Is there any way I can keep my current structure without breaking compatibility with this great plugin? I couldn't find any answer in the documentation or in the source, and issue #64 was closed without commentary, so any help would be greatly appreciated.

My markup:
```html
<div class="basicExample" itemscope itemtype="http://schema.org/ImageGallery">
    <figure itemprop="associatedMedia" itemscope itemtype="http://schema.org/ImageObject">
        <a href="path/to/image1.jpg" itemprop="contentUrl">
            <img src="path/to/image1_thumbnail.jpg" itemprop="thumbnail" alt="Image description" />
        </a>
        <figcaption itemprop="caption description"></figcaption>
    </figure>
</div>
```

**Comment by miromannino** [comment]
This should be possible changing the selector. Have you tried that?
http://miromannino.github.io/Justified-Gallery/options-and-events/

**Comment by Swissendo** [comment]
I'm not shure if I understood the option/example correctly, but adding ```selector: ' > a, > figure',``` fixed the problem, after I edited _justifiedGallery.min_ accordingly. Thanks for the help and the great plugin, donated a few bucks to show my appreciation.

**Comment by miromannino** [comment]
OK, but I suggest you to try the following selector: '> figure, > div:not(.spinner)'. just to avoid problems with the spinner. Thank you for your donation.

**Comment by ftschopp** [comment]
Hi Miro, I tried to use this selector: '> figure, > div:not(.spinner)' but it doesn´t work.
Could you help me?
thanks a lot!
