### ISSUE TITLE
   m, il.;.;.;l;/:?,.. , i9asoaziazaz agg                                                                   h ,b

### ISSUE THREAD

**Issue by ekerner-com** [miromannino/Justified-Gallery#104]

**Comment by ekerner-com** [comment]
OMG sorry, you all just met my 20 month old Daughter :)
Ill try your suggested version update next week and let you know the outcome.

**Comment by miromannino** [comment]
That's fantastic! It's a record :) 
Maybe the youngest person which opened an issue on GitHub!

OK, let me know the outcome. I've tried it with a copy of your Web page, and it works well.

Thank you,

Miro

**Comment by ekerner-com** [comment]
lmao well said! 
You should see what she does to my code if I leave my editor open lol.
Whenever I leave my desk I need to pull my chair away, and if I forget to do so she mountain goats it up there and 'helps' me with my work.
You can see that she encrypts everything tho so I guess it must be top secret.
Thanks, Eugene.
