### ISSUE TITLE
Infinite resizing loop with scrollbar

### ISSUE THREAD

**Issue by pascal-niklaus** [miromannino/Justified-Gallery#106]
I observe an infinite "adjustment" loop (continuous screen flickering) when a vertical scrollbar is added/removed during the gallery building process (e.g. after changing row height, as in http://miromannino.github.io/Justified-Gallery/options-and-events/). I guess this is because the available screen width shrinks when the scroll bar is added, which triggers some recalculations.

This does not occur if 1) no scroll bar is there before and after the operation, or 2) the scroll bar always is present, because there is enough content after the gallery.

**Comment by miromannino** [comment]
See #122
