### ISSUE TITLE
single picture

### ISSUE THREAD

**Issue by XJIOP** [miromannino/Justified-Gallery#113]
version 3.5.4 works perfectly crop through rowHeight, but in 3.6.0 if your gallery has only one photo, it is displayed in full height.

**Comment by miromannino** [comment]
Maybe it depends on the maxRowHeight
Before it was, by default, to 150% of the rowHeight, but now it is 200% by default, because many people thought that JG had a bug cropping the images.

Can you confirm that setting maxRowHeight to, for example "120%" works as you would?
