### ISSUE TITLE
Wrong width/height assumptions for waitThumbnailsLoad

### ISSUE THREAD

**Issue by jrondorf** [miromannino/Justified-Gallery#114]
Reopen #88

In order to get waitThumbnailsLoad, you have to include image height and width information with px unit:
height="70px" width="105px"

But this is an incorrect image tag afterwards: 
http://www.w3schools.com/tags/att_img_width.asp

It must be without px unit
height="70" width="105"

**Comment by miromannino** [comment]
Sorry, the documentation is wrong. Of course the height and width could (and should) be specified without the "px", as HTML wants.

Maybe it was just a mistake of a find&replace of something like 
style="height: 70px; width:105px"
