### ISSUE TITLE
Add "sensitivity" parameter for width changes of gallery before re-building gallery

### ISSUE THREAD

**Issue by th23x** [miromannino/Justified-Gallery#122]
Situation:
I came across a situation, where there is small changes in the width of elements on a page, eg when hiding the scrollbar for some overlay.

Problem:
This then triggers (correctly) also a re-build of the gallery to adapt...but in this case (due to the overlay) and the very marginal change (10-20px) it would look better and safe processing power to just keep the gallery as-is in the background, also avoiding "jumps" due to the repositioning of elements.

Solution / Proposal:
Add a parameter (sensitivity) to the gallery, that can be specified (in px) to alow for some sensitivity before a re-build is triggered. To allow backward compatiblity, this would be of course 0 as default.

In case you consider this, I can also contribute the required code...was already looking in where you compare/ detect width changes...

**Comment by th23x** [comment]
Okay, that would be even a quick one...following adjustments/ additions to the code required in the file `jquery.justifiedGallery.js` (just add the lines marked `// th23 start` to `// th23 end`):

```javascript
  JustifiedGallery.prototype.checkWidth = function () {
    this.checkWidthIntervalId = setInterval($.proxy(function () {
      var galleryWidth = parseInt(this.$gallery.width(), 10);
      // th23 start
      if ((galleryWidth + this.settings.refreshSesitivity) < this.galleryWidth || (galleryWidth - this.settings.refreshSesitivity) > this.galleryWidth) {
      /*
      // th23 end
	  if (this.galleryWidth !== galleryWidth) {
      // th23 start
      */
      // th23 end
        this.galleryWidth = galleryWidth;
        this.rewind();

        // Restart to analyze
        this.startImgAnalyzer(true);
      }
    }, this), this.settings.refreshTime);
  };
```

and

```javascript
    extension: /\.[^.\\/]+$/, // regexp to capture the extension of an image
    refreshTime: 100, // time interval (in ms) to check if the page changes its width
    // th23 start
    refreshSesitivity: 0, // change in width allowed (in px) without re-building the gallery
    // th23 end
    randomize: false,
    sort: false, /*
```

**Comment by miromannino** [comment]
Well done, thank you for the Idea. I think it only happens on OSX when you are not using a mouse, but it could happen.

You can do a pull request, so you will be in the contributors list of the project. 
I would change the if in
```
if (Math.abs(galleryWidth - this.galleryWidth) > this.settings.refreshSensitivity)) {
```  

And then just a check of the new parameter in the:
```
this.checkOrConvertNumber(this.settings, 'refreshSensitivity');
```

And, of course, the name of the option itself, that has a mispelling.

Thank you
Miro

**Comment by th23x** [comment]
Hi Miro,

tried to understand that with the pull requests, but somehow beyond my capabilities...thanks for offering the recognition, but I am more interested in supporting and making things better :-)

So here is the adapted source changes for inclusion in your trunk / repository - just take the lines between `// th23 start` and `// th23 end`, and remove the lines commented out from previous code:

```javascript
  /**
   * Checks the width of the gallery container, to know if a new justification is needed
   */
  JustifiedGallery.prototype.checkWidth = function () {
    this.checkWidthIntervalId = setInterval($.proxy(function () {
      var galleryWidth = parseInt(this.$gallery.width(), 10);
      // th23 start
      if (Math.abs(galleryWidth - this.galleryWidth) > this.settings.refreshSensitivity) {
      /*
      // th23 end
	  if (this.galleryWidth !== galleryWidth) {
      // th23 start
      */
      // th23 end
        this.galleryWidth = galleryWidth;
        this.rewind();

        // Restart to analyze
        this.startImgAnalyzer(true);
      }
    }, this), this.settings.refreshTime);
  };
```

```javascript
    if ($.type(this.settings.fixedHeight) !== 'boolean') throw 'fixedHeight must be a boolean';
    this.checkOrConvertNumber(this.settings, 'imagesAnimationDuration');
    this.checkOrConvertNumber(this.settings, 'refreshTime');
    // th23 start
    this.checkOrConvertNumber(this.settings, 'refreshSensitivity');
    // th23 end
	if ($.type(this.settings.randomize) !== 'boolean') throw 'randomize must be a boolean';
    if ($.type(this.settings.selector) !== 'string') throw 'selector must be a string';
```

```javascript
    extension: /\.[^.\\/]+$/, // regexp to capture the extension of an image
    refreshTime: 100, // time interval (in ms) to check if the page changes its width
    // th23 start
    refreshSensitivity: 0, // change in width allowed (in px) without re-building the gallery
    // th23 end
    randomize: false,
```

**Thanks for the cool script!**

**Comment by no1spirite** [comment]
Hey chaps, I've just come across the same issue (not on OSX either). I've created a pull request based on th23x changes (including your suggestions). Not trying to claim the glory here guys - just wanted it doing.

**Comment by no1spirite** [comment]
Oh yea, love the plugin - thx

**Comment by th23x** [comment]
Thanks no1spirite - no worries who gets mentiond...I don't care, just having this in would be great!

**Comment by no1spirite** [comment]
Hang on. Don't pull yet - Just noticed that this messes the responsive redrawing of the images

**Comment by no1spirite** [comment]
Fixed - sorry about that
