### ISSUE TITLE
Images are some times "loosing" aspect ratio upon initial load

### ISSUE THREAD

**Issue by th23x** [miromannino/Justified-Gallery#123]
Hi there,

I noticed a strange, not always reproducible, but often occuring issue when loading the gallery on my site.

Upon initial load of a page this is the result (also occurs upon "Ctrl + F5" refresh):

![error](https://cloud.githubusercontent.com/assets/13735303/10137774/8a7d6d1a-65fb-11e5-87e9-8e318c8b1214.jpg)

The refresh just hitting "F5" creates the correct view:

![correct-after-refresh](https://cloud.githubusercontent.com/assets/13735303/10137782/8e3a5d64-65fb-11e5-8c8f-99aa2b9d93fa.jpg)

In case you want to try, this is the page I took the above images from: 
http://th23.net/travel/malaysia/

It seems to have to do with the order some images/ scripts are loaded!? But I can't figure out whats wrong as all pictures embedded carry width and height parameters...

**Comment by miromannino** [comment]
Hi can you put a working link, I can only see the images with old-style polaroid frames.

Thank you

**Comment by th23x** [comment]
Oh, sorry for that - the new theme is not yet live, I forgot...here is an interim link:
http://th23.net/travel/malaysia/?theme=th23-twentyfifteen-child

**Comment by miromannino** [comment]
Dear @th23x,

seems that the gallery is a series of

```
    <figure class="gallery-item">
        <div class="gallery-icon portrait">
            <a >
                <img src="...">
            <a>
        </div>
    </figure>
```

I think that JG can't work by default with this format, and maybe, even though you change the selector option, it could have problems to configure that. 

Can you remove the div between the figure and the link?

**Comment by th23x** [comment]
Thanks for investigating - by simplifying the selector, it indeed works as intended :-)

Maybe adding a note in the docs to keep the selector (rather) simple might be an idea, or adding the error and solution to the FAQ?

Great work with the JS!
