### ISSUE TITLE
URL links were manipulated

### ISSUE THREAD

**Issue by Ralphilius** [miromannino/Justified-Gallery#126]
Hello,

I am not using Flickr or any other service to store my images, so the suffixes are not really applicable here. I am not sure how to turn this off since the image urls were removed the last 2 digits. Any suggestion would be greatly appreciated.

Thanks,

**Comment by biziclop** [comment]
http://miromannino.github.io/Justified-Gallery/options-and-events/
says:
"sizeRangeSuffixes default:{ } Describes the suffix for each size range. By default the plugin doesn't search for other thumbnails. "

**Comment by Ralphilius** [comment]
I have tried without the option but the script still loaded with appending suffixes. Should I add `sizeRangeSuffixes: {}` to options when init?

**Comment by biziclop** [comment]
Are you using the latest version?
The `sizeRangeSuffixes` was pre-filled before 3.5:
https://github.com/miromannino/Justified-Gallery#35

**Comment by Ralphilius** [comment]
You're right. It was my bad not to check the version. I was using jsdelivr's cdn which direct to your repo in project page.

Thank you for your time.

**Comment by biziclop** [comment]
Lol, it's not my repo, but you're welcome :)

**Comment by miromannino** [comment]
Thank you @biziclop! Sorry, but I am not really responsive in this period, and I also really thank you for your time. I hope we can collaborate more if you want.

As @biziclop said, the latest version doesn't have prefixes by default. So in this way is simpler for new users. But consider to use this feature if you really need high quality thumbnails of your photos.

Tell me if it is definitely all ok so I can close the issue.

Regards
