### ISSUE TITLE
Infinite scroll deletes last row

### ISSUE THREAD

**Issue by dobromir-hristov** [miromannino/Justified-Gallery#128]
Why does infinite scroll delete the entire last row and then append it back? This makes a horrible jumping up and down effect.
I for example load 50 images each scroll to bottom, and this constant jumping up and down is really unpleasant for a user. Is there a workaround for this? 
Good plugin, allot of settings and all.

**Comment by miromannino** [comment]
behaviour changed, sorry for the late reply. It took 1 hour to change it, but I was very busy in the last months. You can find the new behaviour in the master, and will be released soon in 3.6.1.
Tell me if it's all ok now. Thank you

**Comment by dobromir-hristov** [comment]
Like a charm :smiley:
