### ISSUE TITLE
different size path

### ISSUE THREAD

**Issue by grekpg** [miromannino/Justified-Gallery#133]
how use different path for different size
i try

sizeRangeSuffixes: {
                    100 : '', // used with images which are less than 100px on the longest side
                    240 : '', // used with images which are between 100px and 240px on the longest side
                    320 : '', // ...
                    500 : '',
                    640 : function(e){
                        console.log(e);
                        return '';
                    },
                    1024 : '' // used which images that are more than 640px on the longest side
                }
but it dont work, is possible to put different url ? (it can by .replace but function not surfix.

**Comment by biziclop** [comment]
I think you cannot avoid writing a replacement function for
`$.JustifiedGallery.prototype.newSrc = function (imageSrc, imgWidth, imgHeight)`
to achieve what you want.

Unfortunately, the `JustifiedGallery` object is invisible from the outside, so you have to replace
`  var JustifiedGallery = function ($gallery, settings) {`
to (for example):
`  var JustifiedGallery = $.JustifiedGallery = function ($gallery, settings) {`
or
`!function(a){var b=$.JustifiedGallery = function(b,c){this.settings`
in the minified `jquery.justifiedGallery.min.js` file.

**Comment by grekpg** [comment]
Thank you very much now it work like i need
