### ISSUE TITLE
lastRow: 'center' // 3.6.1

### ISSUE THREAD

**Issue by rrobke** [miromannino/Justified-Gallery#136]
Hey Miro,

thank you very much for this wonderful plugin.

Is there already a release date of the option 'center' for lastRow? We'd really appreciate to have it.

Thanks in advance
Robbie

**Comment by biziclop** [comment]
Hey, it's already there! :)

http://miromannino.github.io/Justified-Gallery/options-and-events/
https://github.com/miromannino/Justified-Gallery/commit/7750de3cbdc88f57fcff475cd26e39272dd83bf6

**Comment by rrobke** [comment]
Thanks, biziclop.

But it is not in the latest release 3.6.0. So we can't load it via bower. :-(

**Comment by miromannino** [comment]
3.6.1 with that option will be available in the next days, sorry for the delay. I hope you understand.

**Comment by rrobke** [comment]
Thanks, Miro. Great news!

**Comment by rrobke** [comment]
@miromannino 
THX. Works like a charm.
