### ISSUE TITLE
Bottom row, wrong sizes

### ISSUE THREAD

**Issue by wezy01** [miromannino/Justified-Gallery#143]
Hi,

I want to use your plugin to show images in a grid, every image with the same width and height.

The problem is that the images in the bottom row are not the same size as those in the other rows.

It can't be the images because if I change the order the problem stays.

This is a part of the code I use:

```
$("#grid").justifiedGallery({
    rowHeight: 180,
    lastRow: 'nojustify',
    maxRowHeight: 180,
    fixedHeight: true,
    captions: false,
    margins: 8,
});
```

Here is a printscreen of my problem

![image](https://cloud.githubusercontent.com/assets/3432279/12590076/616ea8ac-c461-11e5-8075-c1a6aa6c9811.png)

Any ideas how to solve this?

Thanks in advance,
Erwin

**Comment by Rewebify** [comment]
Same Problem here. Last row Images always are smaller. If last row is 3 Images everything is fine. At 1 or 2 images in the last row they are smaller.  If 1 Image per row, then the last image is always smaller.

**Comment by stackcoder** [comment]
I fixed this issue with https://github.com/miromannino/Justified-Gallery/pull/167

**Comment by Beannn** [comment]
I want to know whether you have solved this problem. I always meet this problem. I use the  recent  version, but no use.  Thank you.
