### ISSUE TITLE
Problem with a click bottom

### ISSUE THREAD

**Issue by matanoss** [miromannino/Justified-Gallery#147]
Hello,

I'm Noob in Front end development etc. I've implement to my html file javascript and css files. And I/ve copied The colorbox from this site to my html files

<div id="colorboxExample">
    <a href="image1.jpg">
        <img alt="title 1" src="image1_thumbnail.jpg" />
    </a>
    <a href="image2.jpg">
        <img alt="title 2" src="image2_thumbnail.jpg" />
    </a>
    ...
</div>

<script>
$('#colorboxExample').justifiedGallery({
    lastRow : 'nojustify', 
    rowHeight : 100, 
    rel : 'gallery1', //replace with 'gallery1' the rel attribute of each link
    margins : 1
}).on('jg.complete', function () {
    $(this).find('a').colorbox({
        maxWidth : '80%',
        maxHeight : '80%',
        opacity : 0.8,
        transition : 'elastic',
        current : ''
    });
});

</script>

And I didnt see forward and backward bottom;/ What can I do? I don't know how to do websites, I know only basics of html and CSS. Thanks a lot for sthm code which help me solve my problem :(

**Comment by miromannino** [comment]
The problem is associated to colorbox, or to a wrong use of it.
