### ISSUE TITLE
Publish to NPM?

### ISSUE THREAD

**Issue by alexandernst** [miromannino/Justified-Gallery#158]
Can we get this library to NPM? (npmjs.com)

**Comment by alexandernst** [comment]
Because I needed this published to NPM ASAP, I published it here: https://www.npmjs.com/package/justifiedGallery

I can transfer the ownership of the package as soon as you're willing to take it and keep updating the library.

**Comment by miromannino** [comment]
Can you transfer the ownership to me? My username is miromannino on npm.
Thank you very much.

**Comment by alexandernst** [comment]
Done ;)

**Comment by miromannino** [comment]
Thank you so much @alexandernst 
I will update the new version soon.
