### ISSUE TITLE
Justify issue

### ISSUE THREAD

**Issue by rafasegat** [miromannino/Justified-Gallery#159]
Hello Miro,

Do you know why it is happening?

http://peterbentsen.com/pmb/instagram/

Thanks so much!
Raf

**Comment by rafasegat** [comment]
If resize the page, works well....

**Comment by ugurozturk** [comment]
<div id="seg-instaportfolio-photos-token-YHVgv" class="seg-instaportfolio-photos seg-tiradentes justified-gallery" style="height: 3.35544e+07px;">

You have this. Check codes about the height thing.

**Comment by rafasegat** [comment]
Hi ugurozturk,

Thanks for your response!

Some script is applying that...
