### ISSUE TITLE
Caption always visible

### ISSUE THREAD

**Issue by guazarito** [miromannino/Justified-Gallery#162]
Hi,

Is it possible to keep the caption always visible and not only when hover it?

Thanks in advance..

**Comment by ugurozturk** [comment]
Basicly change the "nonVisibleOpacity : 0.0" to "nonVisibleOpacity : 0.7". 
[dist/js/jquery.justifiedGallery.js#L1118](https://github.com/miromannino/Justified-Gallery/blob/507769101db55a64d415d66a39c6ad8303dd6a0c/dist/js/jquery.justifiedGallery.js#L1118)

Or check the my Fork. I made new features "captionsAnimation" and "captionsShowAlways". Both gets boolean value on the settings like others.

Example

$("#simpletest").justifiedGallery({
	rowHeight: 250,
	maxRowHeight : 450,
	lastRow : 'justify',
	captions : true,
	**captionsShowAlways : true,**
        **captionsAnimation : true,**
        cssAnimation:false,
	margins : 6,
	waitThumbnailsLoad : true
	});
