### ISSUE TITLE
Not functioning

### ISSUE THREAD

**Issue by mayurjobanputra** [miromannino/Justified-Gallery#164]
I know you don't provide support, but hoping you can help me out. I'm trying to get this working on my page. The code is installed and I believe I have done everything correctly, but it's not working as expected.

Scroll down to the photo gallery section: http://makeuptalent.com/makeup-artist/lets-face-it-beauty/

**Comment by IVXCVI** [comment]
It might help if you describe your expectations a little more. Using Brave browser, the three images seem to be displaying as they would properly set up with the software.

i.e. respond to hovering and zoom in to full screen gallery when clicked.

**Comment by miromannino** [comment]
Maybe you should use this plugin instead of the other one :)
