### ISSUE TITLE
Images remain hidden without javascript when justified-gallery class is applied

### ISSUE THREAD

**Issue by glaprida** [miromannino/Justified-Gallery#177]

**Comment by miromannino** [comment]
Yes, that is normal because without this behaviour they would flicker before being justified

**Comment by glaprida** [comment]
I get it... but what if the user has no javascript or its disabled? they won't see any image. It would be great if the images still show up, obviously they wont be justified, but at least they show up.

Would you recommend duplicating the images inside a `noscript` tag?
