### ISSUE TITLE
The newest Justified-Gallery, Bottom row, wrong sizes 

### ISSUE THREAD

**Issue by Beannn** [miromannino/Justified-Gallery#179]
This is a part of the code I use:

	$('#remotetest').justifiedGallery({
						sizeRangeSuffixes: {'lt100':'',
							'lt240':'',
							'lt320':'',
							'lt500':'',
							'lt640':'',
							'lt1024':''},
						rowHeight : 120,
						maxRowHeight: 120,
						target: '_blank',
						justifyThreshold:0.9,
						fixedHeight: true,
						lastRow: 'left',
						rel : 'gallery1', //replace with 'gallery1' the rel attribute of each link
						caption:true,
						captionSettings:{
							animationDuration: 500,
							visibleOpacity: 0.5,
							nonVisibleOpacity: 0.5 },
						margins :20
					});
but  it makes the bottom pictures smaller than other rows,like this:
![qq 20160711104222](https://cloud.githubusercontent.com/assets/4241917/16718743/40ef3ba6-4755-11e6-8533-fa5f12dd9875.png)
Here is a pics of my problem
![qq 20160711104840](https://cloud.githubusercontent.com/assets/4241917/16718766/729bba58-4755-11e6-8c3f-bfae71a57aa4.png)

By the way, I use this fixed version.
![qq 20160711104952](https://cloud.githubusercontent.com/assets/4241917/16718786/ac28add0-4755-11e6-9ee1-c5f0bf80e642.png)

**Comment by miromannino** [comment]
FixedHeight = having the maxRowHeight equals to rowHeight. I am removing the fixedHeight option to avoid misunderstandings.

With lastRow = left that means that the last row is not justified. You shouldn't really need maxRowHeight.

maxRowHeight usually avoid the expansion of the last row if the rowHeight option is very big. I think in your case you don't really need it. I can also think to limit the maxRowHeight only for the last row if it would be more understandable.
