### ISSUE TITLE
Photos sometimes cropped vertically

### ISSUE THREAD

**Issue by skitterm** [miromannino/Justified-Gallery#181]
I have an image gallery that is responsive. I notice that there are times when images are cropped vertically, however. Here's my original gallery:
![original](https://cloud.githubusercontent.com/assets/5875149/16884330/a2057d94-4a7d-11e6-9c1c-259fb3c40c04.JPG)

After squishing the page width smaller, I notice that some images are cropped vertically:
![after](https://cloud.githubusercontent.com/assets/5875149/16884373/e2fea3ca-4a7d-11e6-8742-0e994504f23b.JPG)

The car one is cropped slightly, the tree one is cropped vertically by a lot.

In another case, I have a gallery:
![first](https://cloud.githubusercontent.com/assets/5875149/16884443/47be0ac6-4a7e-11e6-8687-e03b4ad3a269.JPG)

If I switch up the order of the photos (but don't resize the browser), I still get vertical cropping (the light-green plant picture is cropped):
![another](https://cloud.githubusercontent.com/assets/5875149/16884442/47bd2b74-4a7e-11e6-98d8-c63dfd0c3180.JPG)

I notice that if I don't set the maxRowHeight, my images don't seem to crop. In that case, though, the height of the rows varies drastically (I need to cap the row height for consistency).

It would be great if the photos were never cropped vertically! Other than that, I really like this gallery plugin.

**Comment by miromannino** [comment]
Of course maxRowHeight crop the images because to justify the images it would requires to resize them to be bigger. I should write this in the documentation and maybe remove this setting as default.

**Comment by kodjoe** [comment]
hello, 

can you please help me,  how can we respect the ratio and keep the real width, I mean don't exceed the real width ?


when we play with the responsive mode, how can we keep the original ratio without have a superior width than the original ?



example, keep at least 3 images in fullscreen, under 1024px keep 2 and under 500px one by line ?
