### ISSUE TITLE
Making gallery sortable

### ISSUE THREAD

**Issue by byronics** [miromannino/Justified-Gallery#182]
Miro, 

I'm trying to make my galleries sortable and I'm having difficulty integrating Justified Gallery with @voidberg's html5 sortable plugin:  https://github.com/voidberg/html5sortable . I think there are some inherent conflicts with your layout logic and the drag/drop logic.

Have you seen any implementations of Justified Gallery that are sortable using another plugin?  Or have you though about implementing a sortable option?

**Comment by voidberg** [comment]
byronics,

I had the same issue (with another justified gallery plugin though) and in the end I gave up using my plugin and used http://rubaxa.github.io/Sortable/

The experience wasn't smooth in the end but it was pretty ok.

**Comment by miromannino** [comment]
Here an explanation of the options of JG:

[http://miromannino.github.io/Justified-Gallery/options-and-events/](http://miromannino.github.io/Justified-Gallery/options-and-events/)

The option sort can be used. That can also be a generic function.
