### ISSUE TITLE
Toggle outside margins

### ISSUE THREAD

**Issue by Jsewill** [miromannino/Justified-Gallery#199]
It would be nice to have a way to toggle outer margins, or at least negate them with the border property. Currently, I'm using a wrapper element with negative margins to accomplish this, but a proper solution would be much appreciated.

**Comment by ksxio** [comment]
Option `border: 0` isn't sufficient?

**Comment by Jsewill** [comment]
Apparently I did not understand the border option. I'll close this issue, but first, a note for others in case they come across this issue:

  When greater than or equal to 0, the border is set to the value supplied. When negative, uses the value supplied to margins.

**Comment by ksxio** [comment]
Well, the documentation says about border, that:

> Decide the border size of the gallery. With a negative value the border will be the same as the margins.

It's quite clear at least for me...

**Comment by Jsewill** [comment]
Definitely. I am not suggesting any change to documentation. I figure that if I misunderstood it so, others might.
