### ISSUE TITLE
Importing photos from Flickr?

### ISSUE THREAD

**Issue by m4ttr33d** [miromannino/Justified-Gallery#203]
So I am trying to get pictures from a flickr profile into the div (in the example called "mygallery"). How do I put those photos in, and what is the easiest way? I found the code about the sizerange suff and am going to use it as well. I just need photos from Flickr to be displayed in the grid. Thanks!

**Comment by imtehrookie** [comment]
So update, I'm currently using the following code to get the photos. Any ideas how to get it to work with Justified?

``` 
var url = "https://api.flickr.com/services/rest/?&method=flickr.people.getPhotos&api_key=API_KEY&user_id=user_id&format=json&jsoncallback=?";
var src;
$.getJSON(url, function(data){
    $.each(data.photos.photo, function(i,item){
        src = "http://farm"+ item.farm +".static.flickr.com/"+ item.server +"/"+ item.id +"_"+ item.secret +"_m.jpg";
        $("<img/>").attr("src", src).attr("title",item.title).appendTo("#mygallery");
        if ( i == 10 ) return false;
    });
});
```

**Comment by biziclop** [comment]
Hi, try this:
```
#mygallery img {
  position: absolute;
}
```
```
$.getJSON(url, function(data){
  $.each(data.photos.photo, function(i,item){ … });
  $("#mygallery").justifiedGallery({
    selector: 'img',
  });
});
```

**Comment by m4ttr33d** [comment]
Hi, 
So I got it to work and it can be seen in action at rjk.matthewreed.tech.

Matt
