### ISSUE TITLE
Resize not always firing

### ISSUE THREAD

**Issue by lurainsin** [miromannino/Justified-Gallery#206]
Hi,
first of all, thank you for the great work.
I've faced a problem regarding the automatic resize of the gallery: under some condition it will not resize.
In detail, it happen when user resize the window and fire a breakpoint change that cause the scrollbar to be hide/shown. 
Digging inside the code (and in the issues's history of the repo), I've found an issue (#142) and a PR (#151) that introduced this buggy behavior.

In checkWidth method,
`
JustifiedGallery.prototype.checkWidth = function () {
    this.checkWidthIntervalId = setInterval($.proxy(function () {
      var galleryWidth = parseFloat(this.$gallery.width());
      if (hasScrollBar() === scrollBarOn){

        if (Math.abs(galleryWidth - this.galleryWidth) > this.settings.refreshSensitivity) {
          this.galleryWidth = galleryWidth;
          this.rewind();

          // Restart to analyze
          this.startImgAnalyzer(true);
        }
      } else {
        scrollBarOn = hasScrollBar();
        this.galleryWidth = galleryWidth;
      }
    }, this), this.settings.refreshTime); 
 

if there is a scrollbar that before there wasn't, it updates only `scrollBarOn` and also `this.galleryWidth`.

But the next time it will check the width, the resize of the gallery will not happen due the fail of the condition 
` (Math.abs(galleryWidth - this.galleryWidth) > this.settings.refreshSensitivity)`

So, I think the line 470 of justifiedGallery.js need to be removed (`this.galleryWidth = galleryWidth;`) as it cause this behavior.
I am right or I'm missing something?

Thanks

**Comment by martiserra46** [comment]
I did what you said and it worked for me! Thank you!
