### ISSUE TITLE
Negative Margins on img Elements

### ISSUE THREAD

**Issue by mjcampagna** [miromannino/Justified-Gallery#208]
As in the documentation, I'm wrapping my thumbnails in the figure element, then using the selector option to tell the script as much. I've added the element to the CSS as well.

The problem I'm having is that the script continues to apply a negative margin value to the img elements. I've countered this with "margin: 0 !important;" in my CSS, but I'm wondering if there's a better way, for example, prevent the inline styling of margins altogether.

**Comment by venom512** [comment]
I just spent last few hours trying to figure out what causing this. It's ridiculous, but all you have to do is to add **rel="stylesheet"** to JG <link>
