### ISSUE TITLE
Images not arranging properly

### ISSUE THREAD

**Issue by voletiv** [miromannino/Justified-Gallery#209]
I have tried to render your plugin on my website, but even with default settings, I am not able to get a properly arranged grid. This is a screenshot of my website, with 5 images of different sizes to be arranged in a grid:
![screen shot 2017-01-16 at 1 07 08 pm](https://cloud.githubusercontent.com/assets/22424247/21974821/127c0fa4-dbef-11e6-8723-9e0c937b462a.png)

Please let me know how to fix this! Thank you!

**Comment by Etsuni** [comment]
It happens to me too. I fixed it by checking the pass to CSS and if you don't overload it with a custom CSS.
Please check this line `<link rel="stylesheet" href="assets/css/justifiedGallery.min.css" />` to be sure that there are no mistake ;)
