### ISSUE TITLE
Request: Include documentation in repo

### ISSUE THREAD

**Issue by Jwink3101** [miromannino/Justified-Gallery#212]
As I mentioned in my other request, I think that not only is this software awesome, but it is very well documented on your official website. 

Have you considered including this in the actual repository? (or, if I am really that blind, pointing me to it?)

Thanks for the great software!

**Comment by miromannino** [comment]
Hello! Yes, there is a link from the repo to the webpage. But if you didn't find it it's not your fault, but mine :). I will let it to be more visible! 

Thank you for letting me know!

**Comment by Jwink3101** [comment]
I am not sure you understood my point. I was suggesting that the source for the documentation be in the main repo. Not only as a separate site.

**Comment by miromannino** [comment]
Oh now I understand... There is a branch for many github repos for the websites

https://github.com/miromannino/Justified-Gallery/tree/gh-pages

You need just to clone the project and checkout the gh-pages branch to edit the documentation
