### ISSUE TITLE
Gallery not justified for me.

### ISSUE THREAD

**Issue by Hollo1001** [miromannino/Justified-Gallery#215]
Hey,
it would be great if you can help me cause i have searched years after such an awesome gallery.
So my problem is, that the images are not all the same size and not justified.
I tested it on my server. I imported the newest version of jquery and the two files. Do I have to import something else? Here is a test of it https://jsfiddle.net/kx8z85d2/52/
Also if I download the whole project the tests are not working. Thanks for all help I get.
Hollo1001

**Comment by PhilJayN** [comment]
I'm having the same problem with an Express app and ejs. If the page renders the footer.ejs and header.ejs file, the gallery pics are not justified. However, after moving the footer.ejs and header.ejs, the gallery is now justified. Not sure why.
