### ISSUE TITLE
Couple Questions Regarding Use with AJAX Dynamically Adding Images

### ISSUE THREAD

**Issue by deronsizemore** [miromannino/Justified-Gallery#219]
Here's a basic idea of my code which is dynamically adding the new image via AJAX:

```
$('.uploaded-photos').append('<div><img src="' + response.link + '"height="150" class="photo" id="' + response.id + '"/></div>');
$('.uploaded-photos').justifiedGallery('norewind')
```

The initial problem I ran into is that it was rebuilding the gallery each time .justifiedGallery() was called which made the images disappear and that content section to collapse which made things appear to be "flashing" while the images were rebuilt. So, I used "norewind" which seems to have helped with the "flashing" issue, but still one small issue. It appears the .append() is placing the image at the end of the list of images which is fine, but before the image is displayed in the justified gallery, there seems to be a bullet point appear at the end of my container which holds the images. The bullet point appears for a split second and then disappears and my images is appended at that time. The problem is that there's still a slight flicker when that bullet point appears. I see that bullet point which pushes my #footer down, the bullet point disappears which brings my #footer back up. Is there a way to eliminate this little "flicker" which my #footer does when new images are dynamically appended?

The other thing I'd love to be able to do with "norewind' is use .prepend() rather than .append(). It seems like when I try to .prepend() an image dynamically, it never shows up until after a refresh. .append() works fine, but you get the flickering issue I outlined above.

Any help would be greatly appearciated.

**Comment by biziclop** [comment]
The • • • dots are the loading indicator spinner (scroll down to see it):
http://miromannino.github.io/Justified-Gallery/endless-scroll/
I don't see any option to turn it off via some option, but you can try to hide it via css:
```
.mygallery .spinner { display: none !important; }
```

**Comment by deronsizemore** [comment]
Ah, thanks. That makes sense. I knew there was a spinner but wasn't sure why it was showing up with what I was doing since I'm not doing the endless scroll but I see it's associated with norewind option. I'll probably just leave it actually, now that I see what's happening. It was happening so quick on my local environment that I was only seeing a single dot show up with no animation, but on production, there could be a server slow down or something which I'd actually want to see the animations to give the user an indication that something is happening.

Is this spinner simply done with CSS somehow? I wasn't able to find an actual .gif image or anything that creates it. I'd like to maybe change it if possible.

**Comment by biziclop** [comment]
The spinner animations are made with jQuery and hardcoded at `JustifiedGallery.prototype.startLoadingSpinnerAnimation`.
If you are brave, you can customize it by modifying the prototype (or the JG instance), see the 'trick' here: https://github.com/miromannino/Justified-Gallery/issues/218

**Comment by deronsizemore** [comment]
Thanks for all of your help with my questions. I honestly don't feel that brave right now so I think I'll leave it as is. Now that I understand what's happening and that it's actually the desired behavior I think I'm okay with it.
