### ISSUE TITLE
Scroll position not restoring

### ISSUE THREAD

**Issue by anchev** [miromannino/Justified-Gallery#221]
Steps:

1. I am on page containing a justified gallery and I have scrolled down a little, so that I am not right at the top. For example I go to:

https://miromannino.github.io/Justified-Gallery/options-and-events/

Then scroll down to "Options" section, so that the gallery above it just hides.

2. I make the viewport narrower and the page scrolls down
3. I make the viewport wider again but the page doesn't scroll to its previous position

I wonder if there is a way to make it scroll back to the previous position. This can be quite an issue for example when the page contains elements which fire events based on their visibility or based on page scroll position.

**Comment by biziclop** [comment]
Anyone annoyed by this:

Download [Archive.zip](https://github.com/miromannino/Justified-Gallery/files/1451405/Archive.zip)

Open index.html, make it narrow, scroll to the bottom, try resizing.

See code around `__rememberGalleryHeight`.

Probably unreliable code. Contains other unrelated changes for your annoyance.

**Comment by miromannino** [comment]
This should be fixed with the 3.6.5
