### ISSUE TITLE
if I have too many images to load, I need wait long time, but I have 'width' and 'height'

### ISSUE THREAD

**Issue by Ryuurock** [miromannino/Justified-Gallery#226]
I already have 'width' and 'height' for images, can I tell Justified-Gallery plugin, then I don't need to  watch 'spinner',how can I use my images 'width' and 'height' please ?

**Comment by miromannino** [comment]
Have you tried with waithThumbnailsLoad = False?

The info of this are in this page: http://miromannino.github.io/Justified-Gallery/performance-tips/

**Comment by Ryuurock** [comment]
Thanks! I love Justified-Gallery,this is a perfect plugin, I love it
