### ISSUE TITLE
Limit the amount of images showing

### ISSUE THREAD

**Issue by lemonleafan** [miromannino/Justified-Gallery#229]
Hi!
I have this script in my Blogger Template, and it's awesome! Thanks a lot for the work on it.

But, I would like to limit the amount of images that are showed in the preview of my post.
I add an example. I have a total of 7 images in my complete post body, placed along the text, so all of them are showed on the preview, but I want only 2 o 3 to show.
There is any way to limit that?

https://puu.sh/w6JIa/942c763075.jpg

Thanks a lot !

**Comment by miromannino** [comment]
This should be done by your server side implementation. JG only shows what you give to it.
