### ISSUE TITLE
Error message?

### ISSUE THREAD

**Issue by lpf2608005** [miromannino/Justified-Gallery#237]
`$(document).on('scroll',window,function(){  
    $("#justified-gallery").justifiedGallery();
});  `

I use ajax to add html, so I want to reload this plugin, but it is not working.
`Uncaught TypeError: $(...).justifiedGallery is not a function`
Sorry my english is poor.

**Comment by RudyMas** [comment]
Are you sure you have loaded the jquery.justifiedGallery.min.js script already?

This is the typical error you get when you are trying to call a function that hasn't been loaded by your browser yet.
