### ISSUE TITLE
[Mobile only] Swipebox close button event overlays with other events below

### ISSUE THREAD

**Issue by dathdev** [miromannino/Justified-Gallery#242]
This happens with the demo page as well: on mobile, the swipebox close button seems to trigger the burger button below too.
![swipe1](https://user-images.githubusercontent.com/23228315/30853739-dd0c4426-a2d9-11e7-975e-08b9739e8627.png)
![swipe2](https://user-images.githubusercontent.com/23228315/30853756-e3c20f44-a2d9-11e7-856d-0baafdf5db3a.png)

**Comment by miromannino** [comment]
This is related to swipebox/bootstrap compatibility unfortunately
