### ISSUE TITLE
MaxRowHeight not working?

### ISSUE THREAD

**Issue by NatalyR** [miromannino/Justified-Gallery#243]
Hello,

I don't know if i'm doing something wrong but i can't get the row height to be the one asked.
I've set rowHeight and MaxRowHeight at 120, but some row are over 130 pixels, quite none are of 120.
I thought that setting MaxRowHeight would assure me to have the height selected.

Thanks in advance for your help

**Comment by NatalyR** [comment]
Anyone?
Is it still maintained?
I feel like there are no more answers from Miro.

**Comment by biziclop** [comment]
Hi, Miro sometimes pops up, but rarely.
BTW, you keep writing `MaxRowHeight` instead of `maxRowHeight`. In your code do you use the lowercase-first-letter variant?

**Comment by NatalyR** [comment]
Thank you for your answer.
Indeed i was using MaxRowHeight instead maxRowHeight, but it doesn't change anything.
And this is happening on the demo page too (http://miromannino.github.io/Justified-Gallery/options-and-events/).
If you put the same value in RowHeight and maxRowHeight, the pictures height is often higher than the value.

**Comment by NatalyR** [comment]
Here are my options : 

    $("#zone-photos").justifiedGallery({
        rowHeight: 140,
        maxRowHeight: '100%',
        margins: 20,
        captions: true,
        lastRow: 'nojustify',
        waitThumbnailsLoad: true,
        selector: 'div, div:not(.spinner,#photo-open)',
        cssAnimation: false,
        captionSettings: {
            animationDuration: 500,
            visibleOpacity: 1,
            nonVisibleOpacity: 1
        }
    });

**Comment by biziclop** [comment]
Well, you won: it indeed seems to be a bug! As you (and hopefully someday Miro) see it, `newMaxRowHeight.isPercentage` is assigned wrong in both case! So when you set it a numeric string ('120'), it's interpreted as a percent (1.2 * rowHeight), and when you set it as a percentage string ('120%'), it is interpreted as a pixel value (120px). Oops.

Until the bug is officially fixed, you should swap the two `isPercentage = ` assignments in the unminified source.

Here is the original, wrong code:
```
JustifiedGallery.prototype.retrieveMaxRowHeight = function () {
  ...
  if (this.settings.maxRowHeight.match(/^[0-9]+%$/)) {
    newMaxRowHeight.value = parseFloat(this.settings.maxRowHeight.match(/^([0-9]+)%$/)[1]) / 100;
    newMaxRowHeight.isPercentage = false; // *** WHAT ??? ***
  } else {
    newMaxRowHeight.value = parseFloat(this.settings.maxRowHeight);
    newMaxRowHeight.isPercentage = true; // *** WHAT ??? ***
  }
```

**Comment by miromannino** [comment]
I was going around this code to implement a new feature, must be a bug. 
Sorry for my absence. I promise I will work on this starting from next weekend. 
I am just busy

**Comment by miromannino** [comment]
@biziclop thanks for your constant collaboration. You must be included somehow in the contributors somewhere, send me an email

**Comment by NatalyR** [comment]
Thank you a lot @biziclop for your answer, shame on me, i don't have the reflex to check the source code.
Do you mean that i have to swap the false and true assignements?
Or i can use 100 instead of '100%'.
Anyway both method doesn't change the problem, the height is still over the size i've put.

**Comment by biziclop** [comment]
@miromannino: Don't worry about me, I'm just having some fun. My all contributions are public domain. :)
@miromannino + @NatalyR: here are some further modifications, now they seem to work:

```
  JustifiedGallery.prototype.flushRow = function (isLastRow) {
    ...
    if( this.maxRowHeight ){
      var hardRowHeight = this.maxRowHeight.value;
      if( this.maxRowHeight.isPercentage ) hardRowHeight *= settings.rowHeight;

      if( hardRowHeight < this.buildingRow.height )
        this.buildingRow.height = hardRowHeight;

      tr( this.maxRowHeight, hardRowHeight, this.buildingRow.height );
      // R.I.P. if( this.maxRowHeight.value >= settings.rowHeight ) // Stay hungry, stay foolish
    }


  JustifiedGallery.prototype.retrieveMaxRowHeight = function () {
    ...
    // check values
    if (newMaxRowHeight.isPercentage) {
      // Why this check at all? Some people just love things cut in half:
      // https://www.dpreview.com/articles/6922073086/things-we-found-at-cp-2017-which-had-been-cut-in-half
      if (newMaxRowHeight.value < 1) newMaxRowHeight.value = 1;
      //if (newMaxRowHeight.value < 100) newMaxRowHeight.value = 100;
    }
```

**Comment by NatalyR** [comment]
I'm sorry but what is "tr" in flushRow function?
It triggers an error when i apply your modifications (ReferenceError: tr is not defined).

**Comment by biziclop** [comment]
Ooops, it's just my shorthand for `console.log()` :) Delete it.

**Comment by NatalyR** [comment]
(Strange i can't find my answer, so here it is again)
Thank you a lot for your help @biziclop but it still doesn't work for me, height is still over the given value.

**Comment by biziclop** [comment]
You're welcome. :)
If you can, you can try making a very minimal test-case (with your version of JG.js), and attach it here zipped, or upload it somewhere.

**Comment by NatalyR** [comment]
I wouldn't know how to do that (a minimal version of our big project), but thank, i'll keep on searching because if this solved the problem for you (and others) this must comes from my program then.

**Comment by biziclop** [comment]
Then maybe just your JG.zip and your current settings, if they changed since.

**Comment by NatalyR** [comment]
Here they are :
[JG.zip](https://github.com/miromannino/Justified-Gallery/files/1440521/JG.zip)
 
   $("#zone-photos").justifiedGallery({
        rowHeight: 140,
        //rowHeight: <%#= @isize %>,
        maxRowHeight: '100%',
        margins: 20,
        captions: true,
        lastRow: 'nojustify',
        waitThumbnailsLoad: true,
        selector: 'div, div:not(.spinner,#photo-open)',
        cssAnimation: false,
        captionSettings: {
            animationDuration: 500,
            visibleOpacity: 1,
            nonVisibleOpacity: 1
        }
    });

**Comment by NatalyR** [comment]
Actually i've found other uses of justifiedGallery in my CSS files :

//Customize justifiedGallery
.justified-gallery > a > .caption,
.justified-gallery > div:not(#photo-open) > .caption,
.justified-gallery > figure > .caption {
  display: none;
  position: absolute;
  bottom: 0;
  padding: 0;
  background: linear-gradient(transparent, $main_dark_grey);
  left: 0;
  right: 0;
  margin: 0;
  color: white!important;
  font-size: 1em;
  font-weight: 300;
  text-align: center;
}

.justified-gallery > #photo-open {
  position:relative !important;
  display:inline-block;
  overflow:hidden;
  opacity:1;
}

**Comment by biziclop** [comment]
Hi, it seems to work for me using your JG.js: [Archive.zip](https://github.com/miromannino/Justified-Gallery/files/1443068/Archive.zip)

Stupid question, but is it possible that you are still using the minified `jquery.justifiedGallery.min.js` file instead of the repaired one?

I uncommented the `selector: 'div, div:not(.spinner,#photo-open)',` line in the test, but I should note that `div, div:not(whatever)` equals to just `div`.

**Comment by NatalyR** [comment]
I'm not using the minified js, so the problem must come from somewhere else in my code.
But i'm going to remove it to be sure.

I don't understand the "div, div:not(whatever) equals to just div", as it is used to declare what div not to treat as justifiedGallery. If i don't put that i have problem with the div photo-open.
And for the spinner it is written like that in the demo and example on the website, if i'm not wrong.

**Comment by biziclop** [comment]
Maybe some funny CSS somewhere forcing some height or such, maybe with `!important`?

What I wanted to say you should only use `div:not(whatever)` because adding `div, …` selects all div, because the comma `,` behaves like an union/or operator, like `if( element is 'div' OR element is 'div:not(something)' )` which behaves just like `if( element is 'div' )`, unless I was doing something else in the jQuery school when this was discussed. :)
In the Options page you can see `selector`: 'a, div:not(.spinner)'` so there you could use anchors and/or divs, in your case there are only divs which makes it different.

**Comment by NatalyR** [comment]
Of course, i'm stupid, thank you for your explanations :0)
My head is a bit upside down with my big project at the moment (the one where i use Justified Gallery).

Well i'm going to try to find why i have this height problem, thank you for all your help @biziclop  :0)
Just a last question : when you test with my JG.zip, all rows are exactly the same height?
Not as big difference as me (140 to 158 when 140 is the chosen value)

**Comment by biziclop** [comment]
Hi, when I test with the contents of the Archive.zip I uploaded here two days ago (which uses your JG.js) I see exactly 140px high rows in Firefox/Mac and Safari/Mac. Okay, they are 140±1px high.
Does it work for you?

**Comment by NatalyR** [comment]
Oh sorry i thought you were just pointing back to my zip file, i didn't get it was a zip from you and a full demo!
I've downloaded it and opened the index file and rows are not the same height : it goes from 139 to 165 px.
**BUT**, now i've just realized something with your demo because it is clearly visible : it was not the row height that was displayed when i was checking (with Firefox development tool) but the picture height inside the row!
All rows are indeed 140 px but the pictures inside them are sometime taller (being displaying smaller which is a bit confusing, but i'll get it).

So from the beginning i was not looking at the right object height... 
You surely correct the problem of height as i'm quite sure i've seen pictures "a lot" taller than others before, but since then i was still looking at the pictures height when i should have look at the row height (the div element for me).
I'm sorry for the wasted time of our last exchanges, and i'm very very grateful for your help @biziclop , thank you very much for your kind and patience :0)

**Comment by miromannino** [comment]
Note that the fact that JG cut the images in that case is normal. Resizing the images in a way that the width is filled entirely, and a the same time having all images equally rescaled to match a specific height is not always possible. You can try to understand the reason why, just trying to fit even just one image 800x600 in a way that will fill a row of width 1600 and a fixed height of 500. The only way is to distort the images, and of course we don't want that.

**Comment by NatalyR** [comment]
Maybe dealing with the space between the pictures would be a solution?
Well i'm not an expert at all to tell here.
I'm going to check but for the use of the gallery i can't show crop pictures, they have to be exactly how they are.

**Comment by biziclop** [comment]
Hi, don't be sorry, you're welcome! :)
If everything is okay, you can close the issue! :) (Or only Miro can?)
I wish you success with your project!

**Comment by NatalyR** [comment]
Won't it be closed when JG will be corrected?
I let @miromannino decide.

**Comment by biziclop** [comment]
Hi, today's update, I couldn't stop. :)

[Archive.zip](https://github.com/miromannino/Justified-Gallery/files/1451405/Archive.zip)

I added the experimental options `justifyTooTallRowMargins`, `justifyTooTallLastRowMarginsToo`.
If set `true` (as in the above .zip file), images won't be taller than maxRowHeight, instead extra margin will be inserted between the pictures. Experiment with various difference between `rowHeight` and `maxRowHeight` because it can be butt-ugly (depending on the butt). 'muricans with their too regularly spaced false teeth most certainly won't like it.

To @miromannino 
I also couldn't resist and kinda fixed https://github.com/miromannino/Justified-Gallery/issues/221 because while testing it was fucking annoying that it went to the top of the page at every resize.
See code around `__rememberGalleryHeight`.

I should rewrite this whole thing just for fun. I wish I had the time… :)

**Comment by NatalyR** [comment]
You exactly did what i was thinking about and it help me to decide that...it isn't a good idea ;0)
You can see the extra margin and it does not look good, especially with our parameters (140 for the height and 20 for the margin).
But thanks again for this extra work.

It you still want to tweak JG, i really need a way to change (and keep) the height dynamically (i'm not the only one it is an open issue if i'm not wrong).

**Comment by biziclop** [comment]
How do you imagine it exactly?

**Comment by NatalyR** [comment]
Actually i found where my problem was.
I was changing the rowHeight value (according to the user choice) but when the page was refreshed it was back to its value as declared on the js file.
I'm actually rewriting all this js file and everything is working far better ;0P

The only annoying bug that remains for me is the gallery resizing itself in loop when some elements change and this can really last a long time.
But we should go back to the[ issue page ](url=https://github.com/miromannino/Justified-Gallery/issues/106) and not "pollute" this subject ;0)
There is already some exchanges there so there is maybe already a solution.
