### ISSUE TITLE
automatically initialize justified gallery based on html attribute

### ISSUE THREAD

**Issue by eliz82** [miromannino/Justified-Gallery#255]
hello. it's possible to automatically initialize justified gallery without using this kind `$("#basicExample").justifiedGallery(); ` 
of additional javascript? i don't seem to find nothing related to this in the docs.

they are other js libraries ex. lightbox2, fancybox3 that have auto-start.
it will be nice if Justified-Gallery to auto-start without additional javascript code if some specific html attribute is present in the wrapper element. for example` <div class="justified-gallery" data-jg>...</div>`
you can use a certain class or data-...

**Comment by miromannino** [comment]
I don't like this approach. Is attractive for very beginners but this is not a library for very beginners.
I would say any intermediate can deal with the usual jQuery call.
Otherwise I am doing soon some plugins for react and Angular.

Thank you for the idea anyway
