### ISSUE TITLE
Strange vertical margins

### ISSUE THREAD

**Issue by spkrn** [miromannino/Justified-Gallery#257]
Hello,

I noticed in the new version of the plugin, a problem with unequal vertical margins between the thumbs. You can see it in the official exemple :

[http://www.s403089189.onlinehome.fr/Dropshare/Screen-Shot-2017-12-12-13-15-05.png](url)

Do you know what this problem is?

Thanks,
Florent

**Comment by biziclop** [comment]
Hi, you can try my experimental fork:

https://github.com/biziclop/Justified-Gallery/tree/master/src/js
