### ISSUE TITLE
Unable to require this library

### ISSUE THREAD

**Issue by pkid169** [miromannino/Justified-Gallery#260]
After running `npm install --save justifiedGallery`, I was unable to load the lib by doing `require('justifiedGallery')`. Is using `<script src="path/to/justifiedGallery.js">` the only way to load it?

**Comment by miromannino** [comment]
This is a change that I will do in the immediate future. It's a shame that in 2018 there is no support for AMDs still here. But I had a very turbolent 2017 and I couldn't to anything with Justified Gallery. I'll update you soon on this.

**Comment by ericnewton76** [comment]
@miromannino Hey, I'm interested in helping adjust this from AMD to ES6/CommonJS.  We can still produce a build that uses a universal module adapter via factory as well.

What plans have you considered?

**Comment by miromannino** [comment]
@ericnewton76 thanks for offering!

I already done. It's already in master. Under test folder you can find examples for AMD, Browserify and I will put webpack example today/tomorrow. I will release this as 3.7 in the next days.

**Comment by miromannino** [comment]
3.7.0 now should solve this.
Tell me if you have any problem with this.
Thanks

**Comment by evoactivity** [comment]
@miromannino This doesn't seem to be working when using ES6 style "imports" which I was I believe @ericnewton76 was offering to help with.

I'm using ember with the ember-auto-import addon to allow importing from node_modules, so I would expect to be able to just `import 'justifiedGallery';` but that doesn't work.
