### ISSUE TITLE
Margin incorrect at narrow viewport widths

### ISSUE THREAD

**Issue by Toutouwai** [miromannino/Justified-Gallery#275]
There seems to be an issue where margins are not consistent at narrow viewport widths. Images with a wide aspect ratio in particular seem to be affected.

You can observe the issue in the Justified Gallery demo. In the screencast below note how the top margin becomes incorrect (doubled?) on the "mountain road" image at a particular viewport width.

![justified](https://user-images.githubusercontent.com/1538852/39557749-f9b61010-4edd-11e8-8286-5957691de958.gif)

I could reproduce the issue in both Chrome and Firefox, Windows 10.

**Comment by Toutouwai** [comment]
@acwolff, as I said above, the issue is observable **in the Justified Gallery demo**: http://miromannino.github.io/Justified-Gallery/

**Comment by Swissendo** [comment]
I've also had the same problem for a long time and tired to hide it with a small margin, so it wouldn't be that noticeable. It would be wonderful if this bug could be fixed, as it's quite annoying.

**Comment by fireform** [comment]
+1

**Comment by Brodiero** [comment]
+1

**Comment by dandan** [comment]
PR #286 fixed this for me too.
