### ISSUE TITLE
Rotate

### ISSUE THREAD

**Issue by RonaldRimele** [miromannino/Justified-Gallery#278]
Hi,

In the gallery 2 of the images is rotated. I didn't do it so I thinks it's a script.

Can you help me with that?

I don't want it to be rotated, thank you.

**Comment by EarlyOut** [comment]
The script is not manipulating the images in any way. It's just using a simple HTML <img> tag to display the thumbnail image, and adjusting the size of the image to fit in the justified row. Your images probably have incorrect orientation flags, which you will have to deal with in an image-editing application.

**Comment by RonaldRimele** [comment]
Thank you very much, I compressed the image and now it's working well :)
