### ISSUE TITLE
Cannot make the plugin work 

### ISSUE THREAD

**Issue by jessydan** [miromannino/Justified-Gallery#279]
Hi,
I follow all the steps to make the plugins works (imports the files, make the div with the id and the img into it, and call the justifiedGallery, all like the documentation.

But nothing works, nothing appear except three small dots at the beggining (the loading icon i think) but after that nothing, everything is in the code but nothing appear, and the css of the code is not like the documentation, theres missing something.

How can i resolve this issue, i search for like 4 hours but nothing.

Thanks.

**Comment by EarlyOut** [comment]
You're going to have to give us more to go on than just saying, "I can't make it work." A link to a test site would be helpful. In fact, I'd say it's an absolute requirement. We are not mind readers.

**Comment by jessydan** [comment]
Here is the error : 
jquery.justifiedGallery.js:79 Uncaught TypeError: controller.updateEntries is not a function
    at HTMLDivElement.<anonymous> (jquery.justifiedGallery.js:79)

Seems like they don't find my <img> but i do like the documentation says : 

`<div id="paragraph-25" class="container">
    <div id="simpletest" class="justified-gallery">
                           <a href="/sites/default/files/page/fog-1535201_1920.jpg"><img src="/sites/default/files/page/fog-1535201_1920.jpg"></a>                           <a href="/sites/default/files/page/affiche01.jpg"><img src="/sites/default/files/page/affiche01.jpg"></a>                           <a href="/sites/default/files/page/p6180484.jpg"><img src="/sites/default/files/page/p6180484.jpg"></a>                           <a href="/sites/default/files/page/41949943661_70cf935933.jpg"><img src="/sites/default/files/page/41949943661_70cf935933.jpg"></a>                           <a href="/sites/default/files/page/bled-1899264_1920.jpg"><img src="/sites/default/files/page/bled-1899264_1920.jpg"></a>                </div>
</div>` 

And here is my js for launch the gallery : 

jQuery.noConflict();

jQuery("#simpletest").justifiedGallery({rowHeight:200, lastRow: 'justify', margins: 10, captions: false, maxRowHeight:200});

**Comment by jessydan** [comment]
I found the error, but now i have another one, i can use only one gallery per page, when i try to use multiple gallery (with class not id) the plugin doesn't recognize my gallery.
I can't use id because my gallery are generated by drupal, so i can't have the same id (html error) I can only have same classes. 

How to do this ?

**Comment by jessydan** [comment]
I found my error, but i have a little problem, is that the image are showing before resizing, so when i go to my page i see all the images in big screen and then they crop and justified, how can i change this ?

**Comment by acwolff** [comment]
See option waitThumbnailsLoad

**Comment by acwolff** [comment]
As EarlyOut already said, you should give a link, so that other people can test it!

**Comment by biziclop** [comment]
… or you can upload a .zip directly here.
