### ISSUE TITLE
Cant get this to work

### ISSUE THREAD

**Issue by ckarpinski** [miromannino/Justified-Gallery#280]
I have tried using what you have here https://miromannino.github.io/Justified-Gallery/getting-started/ to try this plugin out but I cant get anything to show in the page and have no idea what i am missing. Can you have a look and let me know?
https://codepen.io/ckarpinski/pen/qKORea

thanks!

**Comment by EarlyOut** [comment]
Just for openers, the page has to load jQuery before it calls the Justified Gallery script.

**Comment by ckarpinski** [comment]
Thank you -  I had that on there before but then thought maybe the problem was the justified script had jquery in it, I added a link to Jquery now. Still is not showing anything

**Comment by EarlyOut** [comment]
I just exported your codepen example, and the page works fine. Not sure why it doesn't show anything in codepen.

**Comment by ckarpinski** [comment]
huh, weird, it was also not working on my computer but I did the same downloading it from codepen and it is working. Thanks for testing it and figuring that out for me :)
