### ISSUE TITLE
can you turn off justified gallery for mobile?

### ISSUE THREAD

**Issue by ckarpinski** [miromannino/Justified-Gallery#281]
Is there a way to turn off the justified gallery for mobile? so instead of rows it would just become all the images stacked.

**Comment by EarlyOut** [comment]
There's nothing built into the script to accomplish that.

It's really beyond the scope of this github, but conceptually you need to do two things. First, execute the script only if the window is wider than, say, 650px (trying to detect the actual device type is usually a real mess - using just the viewport width is simpler, and more effective). For example:

```
if ($(window).width() > 650) {
     $("#basicExample").justifiedGallery();
}
```

Then use a CSS media query to supply your own CSS to style the thumbnails if the viewport width is less than 651px.

**Comment by ckarpinski** [comment]
Awesome, thank you so much for the guidance
