### ISSUE TITLE
Release History Notes: v3.7

### ISSUE THREAD

**Issue by leepeterson** [miromannino/Justified-Gallery#283]
Maybe I'm missing it, but I'm unable to find any details about release 3.7 which says "The library could now be used without necessarily defining it as jQuery plugin".

This seems like kind of a major release, no? Something that surely would have more written about it?

Where are the details surrounding this big improvement?

**Comment by miromannino** [comment]
For compatibility issues with older browsers JG still depends on jQuery.
But now you can start not as jQuery plugin, but as a `new JustifiedGallery(...`

I am not trying to remove jQuery once for all. I think is time to say goodbye to older browsers.
