### ISSUE TITLE
Gallery Not Loading on Some Pages

### ISSUE THREAD

**Issue by Seoulinspired** [miromannino/Justified-Gallery#291]
Sorry if this is very obvious, but I don't fully understand the code so please bare with me.

I am having an issue where on some pages the gallery loads fine. Page such as 
https://seoulinspired.com/the-best-sunset-in-seoul/ work fantastically.

However, on other pages the galleries won't load at all:
https://seoulinspired.com/a-photographic-journey-along-the-han-river/
https://seoulinspired.com/night-gallery/

I haven't had this issue before and I am unsure what is causing it. Any help would be very greatly appreciated! 

Thank you

**Comment by EarlyOut** [comment]
I believe you're in the wrong place. This is for issues regarding Miro's JustifiedGallery script: http://miromannino.github.io/Justified-Gallery/. You're using a WordPress plugin with a similar name, but which has nothing to do with this script.
