### ISSUE TITLE
Main wrapper "padding" issue

### ISSUE THREAD

**Issue by test3be** [miromannino/Justified-Gallery#296]
Hi,

Have an issue regarding the main gallery wrapper and i cant get rid of it. As you can see on the screenshot, there is a sort of spacing around the images. I've put a red background on this container to make it more clear. Please see screenshot.

i"m loading:
https://cdnjs.cloudflare.com/ajax/libs/justifiedGallery/3.7.0/css/justifiedGallery.min.css
https://cdnjs.cloudflare.com/ajax/libs/justifiedGallery/3.7.0/js/jquery.justifiedGallery.min.js (before <
<img width="2007" alt="screen shot 2018-12-07 at 08 35 51" src="https://user-images.githubusercontent.com/35294200/49634396-db3bbc00-f9fc-11e8-91ab-34c83876d203.png">
/body>)

My js Init: 

`$(".photo-gallery").justifiedGallery({
    rowHeight: 200,
    //lastRow: 'justify',
    margins: 10,
      image: {
        titleSrc: function(item) {
            return item.el.attr('title') ;
        }
    }
  });`

Thanks for your help

**Comment by biziclop** [comment]
Hi, until a better solution, you could experiment wrapping your `.photo-gallery` like this:

    <div style="background: red; overflow: hidden;">
      <div style="margin: -10px;">
        <div class="photo-gallery justified-gallery">

**Comment by EarlyOut** [comment]
And if you just want to eliminate _all_ spacing between images, set "margins" to zero.

**Comment by Nebel54** [comment]
I just had the same problem and it took me some time to understand the documentation correctly. You need to set `border: 0` to remove those borders:

```
$('.justified-gallery')
    .justifiedGallery({
      margins: 10,
      border: 0
    });
```
