### ISSUE TITLE
Get image caption text from image title or separate tag via jquery selector

### ISSUE THREAD

**Issue by MurzNN** [miromannino/Justified-Gallery#302]
Is it possible to get image caption text not from image `alt` attribute, but from `title` attribute, or separate html tag (via jquery selector)?

**Comment by EarlyOut** [comment]
You can provide your own caption text by including a `<div class="caption">` just after the `<img>` tag.

http://miromannino.github.io/Justified-Gallery/captions/

The script will use the `title `attribute if there's no `alt `attribute, but not having an `alt `attribute is bad practice. To get it to use the `title `attribute in all cases would take a little quick script-hacking, on line 226 of justifiedGallery.js.

**Comment by MurzNN** [comment]
I know that empty `alt` is bad, but in my project `alt` contains text, but we need to display to user longer text from other field. Thanks, via `<div class="caption">` this works well, even with formatting!

**Comment by EarlyOut** [comment]
Yes, I use the explicit caption div - you can load it up with almost anything!
