### ISSUE TITLE
Does this plugin comes with lazyload?

### ISSUE THREAD

**Issue by yelnyaface** [miromannino/Justified-Gallery#316]
hi, does this plugin includes lazyload?

**Comment by EarlyOut** [comment]
See "Infinite Scroll"

https://miromannino.github.io/Justified-Gallery/endless-scroll/

**Comment by kageja** [comment]
Hi, I'd like to get the same effect of Infinite Scroll, that is loading image only if the user scroll down, but non infinite. Last photo ends then scroll.
Thanks in advance
