### ISSUE TITLE
problem with resize window

### ISSUE THREAD

**Issue by GrzegorzNecka** [miromannino/Justified-Gallery#321]
Hi, the gallery is very nice but I have a problem. Sometimes, when I change the window size, the gallery is not refreshed and stays in the same place. Is it possible to fix this problem?

**Comment by EarlyOut** [comment]
I haven't seen this happen. Make sure you have reasonable values set for refreshTime and refreshSensitivity. See, for example, https://jgromit.com/mars/standard/ - try resizing the browser window.

And please give us a link to a page that shows the problem.
