### ISSUE TITLE
Cant make it work

### ISSUE THREAD

**Issue by aero77** [miromannino/Justified-Gallery#323]
I have the following but it wont work.

In the header

```
`<link rel="stylesheet" href="js/css/justifiedGallery.css" />
<script src="js/jquery.justifiedGallery.js"></script>
<script type="application/javascript">

$('#colorboxExample').justifiedGallery({
    lastRow : 'nojustify', 
    rowHeight : 100, 
    rel : 'gallery1', //replace with 'gallery1' the rel attribute of each link
    margins : 1
}).on('jg.complete', function () {
    $(this).find('a').colorbox({
        maxWidth : '80%',
        maxHeight : '80%',
        opacity : 0.8,
        transition : 'elastic',
        current : ''
    });
});

</script>`
```

Unable to post my html but its a div tag with the ID colorboxExample with a link with the IMG tag

**Comment by aero77** [comment]
<div id="colorboxExample">
<?php
		$dbQuery = 'SELECT * FROM photos';
						
		$data = getContent($dbQuery);
			foreach($data as $row) {
				
				echo '<a rel="gallery1" href="http://www.bikedayton.net/photos/'.$row['file'].'">';
				echo '<img src="http://www.bikedayton.net/photos/thumb_'.$row['file'].'"/></a>';	
			}
?>
</div>

**Comment by Sija** [comment]
Of course it doesn't work, since it's in the `<head>`. To make it work you need to either, put it just before the `</body>` tag, or wrap it with `$(document).ready(function() { ... })`
