### ISSUE TITLE
scrollbar problem

### ISSUE THREAD

**Issue by Nic787** [miromannino/Justified-Gallery#328]
Hi,

Justified Gallery doesn't seem to take my scrollbar into consideration. For example, I have a 15px margin on my images and since the container is 100% width, it should be 15px margin on the left and 15px on the right. I can see the margin on the left, but it looks like the margin on the right is hidden behind the scrollbar. How to fix that?

![grid](https://user-images.githubusercontent.com/11185348/78920495-7a454d80-7a61-11ea-9856-3116bb564cad.png)

Thank you

**Comment by miromannino** [comment]
The scrollbar is rendered on top of the page.
To take in consideration that you need to make your html, body, or anyway your main container address that. JG will just be the width: 100% of whatever div it is inside.
