### ISSUE TITLE
Last row centering now far worse than in 3.7.0

### ISSUE THREAD

**Issue by jefftucker1952** [miromannino/Justified-Gallery#329]
Alas, this problem, which my little patch seemed to fix, is now much worse in 3.8.0. The demo:

_(demo removed - 3.8.1 appears to fix the problem)_

Try changing the viewport width. What you'll see is something like this:

![lastrow380](https://user-images.githubusercontent.com/5080907/82612570-2a45c480-9b91-11ea-9f24-992b40ac3196.png)

The one-pixel error is back (at right), and now there are some _new_ unwanted artifacts. The culprit appears to be the changes to lines 187-8 in this commit, but I haven't tested yet: 

https://github.com/miromannino/Justified-Gallery/commit/e11144276b5da15b94af4360253068342510fe8b

ETA: Confirmed. With those two lines restored to their 3.7.0 selves, the behavior is once again correct.

**Comment by miromannino** [comment]
Oh no! I also changed these because I thought they would cause similar issues. 

Can you try updating to 3.8.1?

**Comment by jefftucker1952** [comment]
Yes, that's more like it. It's those last-minute changes that sneak up and bite you. I know about those! ;)

I'm prepping a bunch of updates to my packages that use JG, so I'll incorporate 3.8.1, which will give it a good workout. I'll post back if any new problems crop up. There's one left over from 3.7.0, involving fixed shape thumbnails, but I'll start a new issue, with an updated demo - it's tiny, and it's a fringe case.

**Comment by miromannino** [comment]
Perfect! :)
