### ISSUE TITLE
Separate row height for smartphone/mobile devices

### ISSUE THREAD

**Issue by godfatherjohn** [miromannino/Justified-Gallery#373]
It would be nice to have a separate option to determine the row height for mobile devices. The reason being that an array of images looks good on the desktop but on the phone it simply is one image (full width of screen) per row.

My current workaround is to keep the row height at 100px, this way it is two images per row on a phone and six images per row on the desktop. It is not optimal but I can live with it. It would be nicer to only have 3 per row on the desktop.

**Comment by acwolff** [comment]
I define the rowheight as for instance 15% of the screen.height.

see [this test album](https://andrewolff.jalbum.net/FancyBoxWeb/).

**Comment by godfatherjohn** [comment]
Your workaround is JS to calculate the height and then... ... oh, may pages are becoming messy. ;-)

**Comment by acwolff** [comment]
> Your workaround is JS to calculate the height and then... ... oh, may pages are becoming messy. ;-)

Well my example album is not messy, so apparently you do it in the wrong way!
Why don’t you give a link to yout webpage?

**Comment by godfatherjohn** [comment]
No, it was not meant like that, and surely not as an offence. For some context, I use [Grav CMS](https://getgrav.org) (which I find is [one of] the best CMSs out there). By *messy* I mean the content inside the 'page files' (markdown, backend), not the frontend part. I try to keep as much code outside of the page files. I'm very happy that Justified-Gallery exists!
