### ISSUE TITLE
Rails 4.0 image path issues.. trouble installing

### ISSUE THREAD

**Issue by Jaffery5** [miromannino/Justified-Gallery#39]
Hi, 
I tried to install the JG in a rails 4.0 project. After copying the js & css files. The expected behavior of the images is not as demonstrated, meaning when i click on them they don't pop up and don't have ability to scroll back & forth as it does in the demo. Or does that need a different plugin?

Image ex:
![screen shot 2014-06-28 at 10 14 39 pm](https://cloud.githubusercontent.com/assets/5138809/3422378/c55e3e08-ff33-11e3-9775-1155509ebc22.png)
![screen shot 2014-06-28 at 10 14 49 pm](https://cloud.githubusercontent.com/assets/5138809/3422379/c946f8ac-ff33-11e3-8b9a-24fb30990943.png)

Code:
```
<div id="mygallery" >
  <% @user.portfolios.each do |p| %>      
        <%=link_to image_tag(p.image.url, size: "150x150", :class => "img-rounded img-responsive"), p.image.url %> 
    <% end %>

</div>

<script type="text/javascript">
$(document).ready(function(){
$("#mygallery").justifiedGallery();
});
</script>
```
Thank you

**Comment by vishaltps** [comment]
its not working in my case
i m getting this type of output

..
![screenshot from 2016-02-03 12-26-30](https://cloud.githubusercontent.com/assets/16555538/12775164/d5de5870-ca71-11e5-9c1c-967a1827298b.png)

my code

<div>
	<div class="image-container">
  		<% @uploads.each do |upload|%>
  		<div id="mygallery" class="mygallery">
	<%= image_tag upload.image.url, size: "250x150"  %>
			<%= link_to "Delete", upload , method: :delete %> 
  		</div>
		<%end%>
	</div>
</div>


<script type="text/javascript">

$(document).ready(function(){
	$(".mygallery").justifiedGallery();
});

</script>

**Comment by miromannino** [comment]
Can you send me a link to a working page? Usually it could be just a css rule (e.g. with !important)

**Comment by vishaltps** [comment]
its working now.. i use masonry js nd its working well. thnx
