### ISSUE TITLE
How to set the maximum rows number

### ISSUE THREAD

**Issue by abiku** [miromannino/Justified-Gallery#67]
Hi

It is a great module but it would be great if it have one more option, the possibility to set the maximum rows number. For example I have 15 images and want to display them in 2 justified rows.
Is it hard to add this option to the Justified-Gallery script?

**Comment by miromannino** [comment]
No, it's not hard to do that. For now it's not a feature that is important (I prefer to do other things before), but if you want you can do that and I'm happy to receive a pull request for that.

**Comment by abiku** [comment]
Thanks for the answer.
I've just looked into the code and unfortunately it is to hard for me.
I even cannot find the place where you are calculating the rows number for the images.
Is it possible you give me some hints? I will really appreciate!

**Comment by miromannino** [comment]
Just another question for what you want. Do you want that ALL the images is shown in two justified rows? Or do you want that the plugin is stopped when 2 rows have made, hiding the other images?

**Comment by abiku** [comment]
All images, no matter how many, 15,20 or 50. want to display them all justified in a specific number of rows. of course number of images must be greater or equal to rows number

**Comment by ttseng** [comment]
+1 this would be a really helpful feature to have

**Comment by miromannino** [comment]
The problem with this feature is that is very hard to do. Just because the problem you are describing is NP-complete.
