### ISSUE TITLE
Option to re-initialise

### ISSUE THREAD

**Issue by danbramall** [miromannino/Justified-Gallery#68]
Hi,

I'd like to use Justified Gallery on a page that will be adding/removing thumbnails dynamically with AJAX.  There doesn't appear to be an option to re-initialise the plug-in after a DOM change.  It would be extremely handy to have this option.

**Comment by miromannino** [comment]
Yes, just call again justifiedGallery without any option; it has all the settings saved and you don't need to pass them again.

    $('#gallery').justifiedGallery()

But, if you have added thumbnails only at the bottom call it in this way: 

    $('#gallery').justifiedGallery('norewind')

P.S. I know, this thing is not written anywhere in the new site. Only the "norewind" option is visible in the documentation [infinite scroll page](http://miromannino.github.io/Justified-Gallery/endless-scroll/).
I will add it as soon as possible. Thank you for the question.

**Comment by danbramall** [comment]
Very helpful, thanks! :)

**Comment by dupuchba** [comment]
I have the same issue, please help. I have a select option that trigger a loading on every change. I have to reload completely the image BUT it doesn't display it

```
$('#sportSelect').on('change', function(e) {     
var sport = $(this).val();     
$.ajax({        
 type: "GET",         
 url: Routing.generate('sportbook_view_images'),         
 data: {sport: sport},         
 success: function(data) {             
  $("#sportbookGallery").justifiedGallery();             
  $('#sportbookGallery').html(data);         
 }     
});  });
```

The photo is here but not displayed...

![capture d ecran 2015-01-21 a 14 36 52](https://cloud.githubusercontent.com/assets/911705/5836928/fe46109e-a17a-11e4-980a-43cd8be28360.png)

**Comment by danbramall** [comment]
Would it be as simple as swapping the two lines as follows?:

    $('#sportbookGallery').html(data);
    $("#sportbookGallery").justifiedGallery();

So this first loads the HTML obtained from the AJAX request, THEN calls justifiedGallery() on that data.

**Comment by dupuchba** [comment]
Thanks ! 
Can't believe I lost that much time ^^
