### ISSUE TITLE
Non image element in justified gallery

### ISSUE THREAD

**Issue by davidb2002** [miromannino/Justified-Gallery#70]
Fantastic script! Extremely useful now with the inclusion of infinite scroll usage.

I'm wanting to occasionally insert a non-image element into the gallery during infinite scroll. In my case, I want to add a banner similar to what flickr does. However, when I 'append' to the gallery container, the script just returns 'null'. I suppose its trying to get the correct size of the image which isn't there as it's an iframe.

**Comment by klihelp** [comment]
Until official solution is coming, insert a transparent image with the size required..

**Comment by miromannino** [comment]
Available in 3.6
