### ISSUE TITLE
Add DocBlock comments to all functions for easier reading and modifying

### ISSUE THREAD

**Issue by davidb2002** [miromannino/Justified-Gallery#72]
I'm trying to make some edits to the js code, but due to the lack of commenting, it's providing very hard to understand what everything is doing. I suggest using docblocks on all functions as a starting point to description what each function does and what arguments they receive.

**Comment by miromannino** [comment]
OK, I know that the code could be considered a little bit tricky. I'll add some comments to help more who want to extend the functionalities.
