### ISSUE TITLE
feature requests

### ISSUE THREAD

**Issue by git-marijus** [miromannino/Justified-Gallery#73]
1. an option to exclude certain elements in gallery from beeing processed (like you do with .spinner). 
2. an option to not have the "new" outer margin (like pre 3.5).
   thank you...

**Comment by stackcoder** [comment]
I added an option to disable the "new outer margin". See: https://github.com/miromannino/Justified-Gallery/pull/74

**Comment by git-marijus** [comment]
thanks a lot @stackcoder i hope that will be merged soon...
the reason for feature 1. might not be obvious but it is helpful if there need to be other other elemnts inside the gallery. for example some autoload implementations need an empty div inside the gallery...

**Comment by stackcoder** [comment]
Yes, the first one would be also great for something like a full row preview.
I don't know exactly what kind of autoloader requires this (and Justified-Gallery already have one) but you should be able to wrap the image and overlay it (like captions do).
