### ISSUE TITLE
"More" button - how to implement

### ISSUE THREAD

**Issue by Panart** [miromannino/Justified-Gallery#77]
Hi! Thanks for your great script, but I need to have a Load More button, while pressing it will load more images. I can't figure out how to do that. Please help)

P.S. That's some sort of the issue I'd like to have: http://www.jqueryscript.net/demo/jQuery-Plugin-To-Create-An-Instagram-Photo-Gallery/

**Comment by miromannino** [comment]
Have you seen this one?

http://miromannino.github.io/Justified-Gallery/endless-scroll/
