### ISSUE TITLE
waitThumbnailsLoad

### ISSUE THREAD

**Issue by jrondorf** [miromannino/Justified-Gallery#88]
I have a problem with the option waitThumbnailsLoad.

I want to have the UI build directly, and the thumbs should appear randomly as there are loaded. Must this property then be true or false?

I guess this explanation is wrong: http://miromannino.github.io/Justified-Gallery/performance-tips/

It must be w/o px:
<img src="path/to/img.jpg" height="70" width="105" />

http://www.w3schools.com/tags/att_img_width.asp

**Comment by miromannino** [comment]
Yes, you are right. To have better performances one needs to have waitThumbnailsLoad to false. I will explain this better.

**Comment by jrondorf** [comment]
Thanks.
It would be nice if you could build a test page where this is set to false, and where it is visible how the layout is build before the thumbnails are loaded. I never was able to get it working correctly.
