### ISSUE TITLE
Infine scroll and randomize leave empty gaps

### ISSUE THREAD

**Issue by fperezpellicena** [miromannino/Justified-Gallery#95]
The infine-scroll functionality combined with the randomize property, create blank 'gaps' in between the original images.
It also depends on the width of the gallery. 
If the browser is resized, the gallery removes the empty gaps and shows up fine.

To test this case:
 - Add randomize: true property to the original gallery properties
 - Add some more images to the example norewind_loaded_images.html.

Tested in:
 - Chrome 43.0.2357.81 (64-bit)
 - Chrome 45.0.2421.0 dev (64-bit)
 - Firefox 38.0

**Comment by miromannino** [comment]
Have you tried with the [3.6](https://github.com/miromannino/Justified-Gallery/tree/v3.6)? That is in beta, but is available and some of those error are corrected.
Tell me.

**Comment by fperezpellicena** [comment]
Yes, you're right, the error I mentioned is corrected in v3.6.

Thank you very much for your support.
